### ISSUE TITLE
Invalid argument: Column family not found: : col5

### ISSUE THREAD

**Issue by cedricfung** [openethereum/3.1-db-upgrade-tool#16] opened 2021-04-14 06:47 UTC
```
     Running `target/debug/oe-upgrade-db-3-1 /data/io.parity.ethereum/chains/ethereum/db/906a34e69aec8c0d/overlayrecent`
Migrating database from v15 (3.0 series) to v16 (3.1 series).
CAUTION: This will update the database in a non reversible way. A backup is recommended. 
type I AGREE to proceed > I AGREE
- opening the database...
             Error: Io(Custom { kind: Other, error: Error { message: "Invalid argument: Column family not found: : col5" } })
```

**Comment by Legogris** [comment] 2021-04-14 11:09
Exactly the same here. Upgrading from 3.0.1 mainnet archive node

Testnet fast sync nodes upgraded fine

**Comment by Legogris** [comment] 2021-04-14 11:10
Duplicate of #12

**Closed** 2021-04-14 15:34 UTC
Labels: duplicate
